### ISSUE TITLE
issue with python3.8

### ISSUE THREAD

**Issue by raybellwaves** [philipschall/shapelysmooth#2]
`geometry: Union[LineString, Polygon, list[tuple[float, float]]]` https://github.com/philipschall/shapelysmooth/blob/main/shapelysmooth/__init__.py#L7 gives

TypeError: 'type' object is not subscriptable.

Works ok for python3.9.

Not sure if https://github.com/philipschall/shapelysmooth/blob/main/setup.py#L25 fully holds

**Comment by philipschall** [comment]
Should be fixed in: 138188c0707078a25291473a25daea8756cca962 by making proper use of collections in the 'typing' module.
