### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by cheginit** [philipschall/shapelysmooth#6]
It would be great if building `arm64` can be added to the `conda-forge` pipeline so it can be both installed with `mamba`.

Edit: I realized that it can be installed with `pip`.

**Comment by cheginit** [comment]
I found the instruction for adding `osx-arm64` [here](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock). I can open a PR on the feedstock, if interested.

**Comment by raybellwaves** [comment]
Welcome to raise an issue and/or PR in the feedstock repo

**Comment by cheginit** [comment]
My [PR](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5230) for adding `arm64` has been merged on `conda-forge`. So, I think an automatic PR with necessary changes will be opened on `shapelysmooth`'s feedstock.

**Comment by cheginit** [comment]
Ah, I just noticed that you have already merged it. Thanks!
