### ISSUE TITLE
v0.2.0 on conda-forge

### ISSUE THREAD

**Issue by cheginit** [philipschall/shapelysmooth#9]
I noticed that the version on `conda-forge` is not the latest. I checked the feedstock and realized that the reason the release bot hasn't opened a PR for the new release yet, is that there's no source release on `pypi` for [v0.2.0](https://pypi.org/project/shapelysmooth/#files). So, I think for some reason, the release workflow does not build the source file and only generates wheels.

**Comment by philipschall** [comment]
Thanks for pointing it out. Should be all good now with v.0.2.1.

**Comment by cheginit** [comment]
Awesome, thanks!

Though, the last step of the new workflow [failed](https://github.com/philipschall/shapelysmooth/actions/runs/9782498925/job/27009528741).
